Winerama/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    re_path(r'reviews/', include('reviews.urls', namespace="reviews")),
    path('admin/', admin.site.urls),
]

reviews/urls.py
from django.urls import include,path,re_path
from . import views

app_name = 'reviews'

urlpatterns = [
    re_path(r'^$',views.review_list,name = 'review_list'),
    re_path(r'^review/(?P<review_id>[0-9]+)/$',views.review_detail,name = 'review_detail'),
    re_path(r'^wine$', views.wine_list, name='wine_list'),
    re_path(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    re_path(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
]

reviews/models.py
from django.db import models
import numpy as np
# Create your models here.
class Wine(models.Model):
    name = models.CharField(max_length=200)

    def average_rating(self):
        # all_ratings = map(lambda x: x.rating,self.review_set.all())
        all_ratings = []
        for review in self.review_set.all():
            all_ratings.append(review.rating)
        return np.mean(all_ratings)

    def __str__(self):
        # 默认使用哪个属性，显示模型的简单表示
        return self.name

class Review(models.Model):
    RATING_CHOICES = (
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
    )
    wine = models.ForeignKey(Wine, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['user_name', 'rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

reviews/views.py
from django.shortcuts import get_object_or_404, render
from .models import Review, Wine
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import ReviewForm
import datetime

# Create your views here.



def review_list(request):
    # - 号表示降序
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def wine_list(request):
    wine_list = Wine.objects.order_by('-name')
    context = {'wine_list':wine_list}
    return render(request, 'reviews/wine_list.html', context)


def wine_detail(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm()
    return render(request, 'reviews/wine_detail.html', {'wine': wine})

def add_review(request,wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    # form = ReviewForm(request.POST)
    if request.method != 'POST':
        form = ReviewForm()
    else:
        form = ReviewForm(request.POST)
        if form.is_valid():

            rating = form.cleaned_data['rating']
            comment = form.cleaned_data['comment']
            user_name = form.cleaned_data['user_name']
            review = Review()
            review.wine = wine
            review.user_name = user_name
            review.rating = rating
            review.comment = comment
            review.pub_date = datetime.datetime.now()
            review.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))
    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})

reviews/templates/reviews/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reviews</title>
{% bootstrap_css %}
{% bootstrap_javascript %}
</head>
<body>


{% block bootstrap3_content %}

<div class = 'container'>
    <nav class = 'navbar navbar-default'>
        <div class = 'navbar-header'>
            <a class = 'navbar-brand' href = "{% url 'reviews:review_list' %}">Winerame</a>
        </div>
        <div id = 'navbar' class = 'navbar-collapse collapse'>
            <ul class = 'nav navbar-nav'>
                <li><a href = "{% url 'reviews:wine_list' %}">Wine List</a></li>
                <li><a href = "{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
        </div>
    </nav>
    <h1>{% block title %}(no title){% endblock %}</h1>
    {% bootstrap_messages %}
    {% block content %}(no content){% endblock %}
</div>
{% endblock %}
</body>
</html>

reviews/templates/reviews/review_detail.html
{% extends 'reviews/base.html' %}
{% block title %}
    <h2>Review Detail</h2>
{% endblock %}
{% block content %}
    <div>
        <p>Wine name: {{review.wine}}</p>
        <p>Rating: {{review.rating}}</p>
        <p>Comment: {{review.comment}}</p>
    </div>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'reviews/base.html' %}
{% block title %}
    <h2>Latest reviews</h2>
{% endblock %}
{% block content %}
{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/wine_detail.html
{% extends 'reviews/base.html' %}
{% load bootstrap3 %}

{% block title %}
    <h2>Wine Detail</h2>
{% endblock   %}

{% block content %}
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>


<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div>
    {% for review in wine.review_set.all %}
    <div>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' wine.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>
{% endblock  %}


<!--使用该部分，则出现错误：Parameter "form" should contain a valid Django Form-->
<!--
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
<h3>Recent reviews</h3>
{% if wine.review_set.all %}
<div class = 'row'>
    {% for review in wine.review_set.all %}
    <div class = 'col-xs-6 col-lg-4'>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}
<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'reviews:add_review' wine.id %}" method="post" class = 'form'>
    {% csrf_token %}
    {% bootstrap_form form layout="inline"  %}
    {% buttons %}
    <button class = 'btn btn-primary' name="submit">
         {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
-->

reviews/templates/reviews/wine_list.html
{% extends 'reviews/base.html' %}
{% block title %}
    <h2>Wine List</h2>
{% endblock %}
{% block content %}
{% if wine_list %}
<div>
    {% for wine in wine_list %}
        <div>
            <a href ="{% url 'reviews:wine_detail' wine.id %}">{{wine.name}}</a>
        </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}